"""Feature ② — export the decision brief to PDF / Word (both fully offline).

Renders the SAME figures the engine produced (no recomputation): the headline
number + range, the narrated brief, the recommended chart, the sources, and the
standing disclaimer. PDF uses reportlab; Word uses python-docx. Returned as raw
bytes for a file download.
"""
import io
import re

FOOTER = ("Generated by WaitCost · HUD 2024 PIT · Census ACS 2024 (API) · figures are ranges.")
SOURCES = ("HUD 2024 PIT CoC Population & Subpopulation · US Census ACS 2024 1-yr (API) · "
           "HUD System Performance Measures FY2023 · Economic Roundtable (2024$).")
DISCLAIMER = ("This tool informs a budget-timing tradeoff. It does not decide allocations "
              "or forecast individuals. All figures are ranges, not predictions.")


def _strip_md(text):
    """Light markdown -> plain text (bold/headers/list markers) for body prose."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"^>\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"^[-*]\s+", "• ", text, flags=re.MULTILINE)
    return text


def _headline(result):
    """The one-line headline answer (markdown stripped), or a sensible default."""
    d = result.get("direct_answer")
    return _strip_md(d).strip() if d else "See decision brief below."


def chart_table(result):
    """Extract a compact (labels, values, value_label) view of the recommended
    chart's first numeric series — used to render a small chart/table in the export."""
    try:
        from api import payloads as P
        name = result.get("recommended_chart") or "cost_trajectory"
        coc = _coc(result)
        budget = float(result.get("plan", {}).get("budget_musd", 50.0))
        delay = int(result.get("plan", {}).get("delay_years", 3) or 0)
        spec = P.chart_payload(name, coc=coc, budget=budget, delay=max(delay, 1))
        s = (spec.get("series") or [{}])[0]
        x, y = s.get("x"), s.get("y")
        # numeric y -> labels=x; else numeric x (horizontal/tornado) -> labels=y
        if isinstance(y, list) and y and all(isinstance(v, (int, float)) for v in y):
            labels, values = [str(v) for v in x], [float(v) for v in y]
        elif isinstance(x, list) and x and all(isinstance(v, (int, float)) for v in x):
            labels, values = [str(v) for v in y], [float(v) for v in x]
        else:
            return None
        return {"title": spec.get("title", name), "y_label": spec.get("y_label", ""),
                "labels": labels[:12], "values": values[:12]}
    except Exception:
        return None


def _coc(result):
    runs = result.get("runs") or {}
    # CoC isn't on the top-level result; recover it from the plan question / default.
    m = re.search(r"([A-Z]{2}-\d{3})", str(result.get("plan", {}).get("question", "")))
    return m.group(1) if m else "CA-600"


# --------------------------------------------------------------------------- #
def build_docx(result):
    from docx import Document
    from docx.shared import Pt, RGBColor

    doc = Document()
    doc.add_heading("WaitCost — Decision Brief", level=0)

    q = result.get("plan", {}).get("question") or result.get("question", "")
    meta = doc.add_paragraph()
    meta.add_run("Question: ").bold = True
    meta.add_run(str(q))

    doc.add_heading("Headline", level=1)
    h = doc.add_paragraph(_headline(result))
    h.runs[0].bold = True

    chart = chart_table(result)
    if chart:
        doc.add_heading(f"Recommended chart — {chart['title']}", level=1)
        t = doc.add_table(rows=1, cols=2)
        t.style = "Light Grid Accent 1"
        hdr = t.rows[0].cells
        hdr[0].text, hdr[1].text = "Category", chart["y_label"] or "Value"
        for lab, val in zip(chart["labels"], chart["values"]):
            row = t.add_row().cells
            row[0].text, row[1].text = lab, f"{val:,.1f}"

    doc.add_heading("Full brief", level=1)
    for block in _strip_md(result.get("brief_markdown", "")).split("\n"):
        if block.strip():
            doc.add_paragraph(block)

    doc.add_heading("Sources", level=1)
    doc.add_paragraph(SOURCES)
    disc = doc.add_paragraph(DISCLAIMER)
    disc.runs[0].italic = True
    foot = doc.add_paragraph(FOOTER)
    foot.runs[0].font.size = Pt(8)
    foot.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_pdf(result):
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                    TableStyle)
    from reportlab.graphics.shapes import Drawing
    from reportlab.graphics.charts.barcharts import VerticalBarChart

    styles = getSampleStyleSheet()
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=8,
                           textColor=colors.grey)
    buf = io.BytesIO()
    docp = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.7 * inch,
                             bottomMargin=0.7 * inch)
    flow = [Paragraph("WaitCost — Decision Brief", styles["Title"])]

    q = result.get("plan", {}).get("question") or result.get("question", "")
    flow.append(Paragraph(f"<b>Question:</b> {q}", styles["Normal"]))
    flow.append(Spacer(1, 8))
    flow.append(Paragraph("<b>Headline</b>", styles["Heading2"]))
    flow.append(Paragraph(_headline(result), styles["Normal"]))
    flow.append(Spacer(1, 8))

    chart = chart_table(result)
    if chart:
        flow.append(Paragraph(f"<b>Recommended chart — {chart['title']}</b>", styles["Heading2"]))
        d = Drawing(440, 200)
        bc = VerticalBarChart()
        bc.x, bc.y, bc.width, bc.height = 30, 25, 390, 150
        bc.data = [chart["values"]]
        bc.categoryAxis.categoryNames = chart["labels"]
        bc.categoryAxis.labels.angle = 30
        bc.categoryAxis.labels.dy = -6
        bc.barWidth = 6
        bc.valueAxis.valueMin = min(0, min(chart["values"]))
        bc.bars[0].fillColor = colors.HexColor("#1a73e8")
        d.add(bc)
        flow.append(d)
        flow.append(Spacer(1, 8))

    flow.append(Paragraph("<b>Full brief</b>", styles["Heading2"]))
    for block in _strip_md(result.get("brief_markdown", "")).split("\n"):
        if block.strip():
            flow.append(Paragraph(block.replace("&", "&amp;"), styles["Normal"]))
            flow.append(Spacer(1, 2))

    flow.append(Spacer(1, 10))
    flow.append(Paragraph("<b>Sources</b>", styles["Heading2"]))
    flow.append(Paragraph(SOURCES, styles["Normal"]))
    flow.append(Spacer(1, 6))
    flow.append(Paragraph("<i>" + DISCLAIMER + "</i>", styles["Normal"]))
    flow.append(Spacer(1, 6))
    flow.append(Paragraph(FOOTER, small))

    docp.build(flow)
    return buf.getvalue()
